version: 'latest'
services:
  ssps:
    image: quay.io/minio/minio
    container_name: ssps
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
    command: server /data --console-address ":9001"
