name: test SSH EC2 
run-name: ${{ github.actor }} is trying to SSH to EC2

on: 
    push:
        branches: [test-deploy]

jobs: 
    push-images-to-server: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repository 
              uses: actions/checkout@v3
            
            - name: create .env
              env: 
                ENV: ${{ secrets.ENV }} 
              run: echo "$ENV" | base64 -d > .env

            - name: login dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build docker image 
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ssps-be . 
            
            - name: push docker hub 
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ssps-be

            - name: create pem file 
              env:
                EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }} 
              run: | 
                echo "$EC2_PEM_KEY" | base64 -d > my-server.pem
                chmod 400 my-server.pem
                
            - name: ssh to server 
              run: | 
                ssh -o StrictHostKeyChecking=no -i "my-server.pem" ubuntu@ec2-54-169-143-19.ap-southeast-1.compute.amazonaws.com << EOF
                  cd /home/ubuntu
                  sudo docker-compose down 
                  sudo docker-compose pull 
                  sudo docker-compose up -d
                  sudo docker system prune -f
                EOF
              